//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPruebaTecnica.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class CantanteSongs
    {
      
        public int idInter { get; set; }

        public Nullable<int> idCantante { get; set; }
       
        public Nullable<int> idSong { get; set; }
        
        public virtual Cantante Cantante { get; set; }
        
        public virtual songs songs { get; set; }
    }
}
